# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l-58DapU8CQJrp78O70Bny6Hk8zVl_Qj
"""

import streamlit as st
import pandas as pd
import random

# --- 設定網頁 ---
st.title("🧩 社會心理學：自動題庫練習")
st.write("題目會自動從題庫中隨機抽出，並自動生成錯誤選項！")

# --- 1. 讀取資料 ---
# 加上 @st.cache_data 讓資料讀取一次就好，網頁跑比較快
@st.cache_data
def load_data():
    # 這裡的檔名必須跟你上傳到 GitHub 的 csv 檔名一模一樣
    # 預設 Pandas 會把 CSV 讀成 DataFrame
    df = pd.read_csv("scusocpsy.csv")
    return df

try:
    df = load_data()
except Exception as e:
    st.error(f"找不到 data.csv 檔案，請確定你有上傳 CSV 到 GitHub！錯誤訊息：{e}")
    st.stop()

# 確保資料量足夠 (至少要有 4 個名詞才能湊出 1 個正解 + 3 個誘答)
if len(df) < 4:
    st.warning("題庫裡的資料太少了！請至少準備 4 個名詞解釋。")
    st.stop()

# --- 2. 初始化 Session State (用來記住現在題目是什麼) ---
# Streamlit 每次按按鈕都會重跑，所以要用 Session State 記住現在是哪一題，不然題目會一直亂跳
if 'current_question' not in st.session_state:
    st.session_state.current_question = None
if 'options' not in st.session_state:
    st.session_state.options = []
if 'correct_answer' not in st.session_state:
    st.session_state.correct_answer = None

# --- 3. 出題邏輯函數 ---
def generate_question():
    # 隨機選一個名詞當題目 (row 是一整列資料)
    question_row = df.sample(1).iloc[0]
    correct_term = question_row['term']      # 正確名詞
    question_text = question_row['definition'] # 題目(解釋)

    # 從剩下的資料中，隨機選 3 個錯誤的名詞
    # df[df['term'] != correct_term] 意思是「過濾掉正確答案的那一行」
    wrong_options = df[df['term'] != correct_term]['term'].sample(3).tolist()

    # 組合選項：1個正解 + 3個錯的
    all_options = wrong_options + [correct_term]
    random.shuffle(all_options) # 把選項順序打亂

    # 存入 Session State
    st.session_state.current_question = question_text
    st.session_state.correct_answer = correct_term
    st.session_state.options = all_options
    # 清除之前的選擇與結果
    st.session_state.user_submitted = False

# 如果剛進來網頁還沒題目，就出一題
if st.session_state.current_question is None:
    generate_question()

# --- 4. 顯示題目區域 ---
st.markdown("### 題目：")
st.info(st.session_state.current_question)

# 顯示選項 Radio Button
user_choice = st.radio("請選擇正確的名詞：", st.session_state.options)

# --- 5. 送出與結果 ---
if st.button("送出答案"):
    st.session_state.user_submitted = True

if st.session_state.get('user_submitted'):
    if user_choice == st.session_state.correct_answer:
        st.balloons()
        st.success(f"✅ 答對了！答案就是 **{st.session_state.correct_answer}**")
    else:
        st.error(f"❌ 答錯囉！正確答案是：**{st.session_state.correct_answer}**")

    st.markdown("---")
    # 下一題按鈕
    if st.button("下一題 ➡️"):
        generate_question() # 重新抽題
        st.rerun() # 重新整理頁面